wne,wn,n,sn,sne,wn,sn,sn,sn,n,sn,ne,wn,sn,sn,ne,wn,sn,ne,wne
we,we,we,wn,sn,se,wn,n,sne,we,wne,sw,se,wne,wn,se,sw,ne,we,we
we,swe,sw,s,ne,swn,e,swe,wn,se,w,sn,sn,s,se,wn,sn,se,we,we
sw,ne,wn,ne,sw,sn,se,wn,se,wne,we,wn,sn,sn,sn,e,wn,sne,sw,e
wn,se,we,sw,sn,sn,sn,se,wn,e,we,swe,wn,sn,sn,se,w,sn,sn,se
sw,ne,we,wne,wn,n,sne,wn,se,we,we,wn,se,wn,sn,sne,sw,ne,swn,ne
wne,sw,se,we,we,we,wn,se,wne,we,we,we,swn,e,wn,sn,sn,se,wn,e
we,wn,sn,s,se,sw,se,wn,se,sw,se,sw,ne,we,we,wn,sn,sn,se,we
we,sw,sn,ne,swn,n,ne,sw,n,ne,wn,sn,se,w,se,sw,ne,wn,ne,we
sw,sn,sn,s,sn,se,sw,sn,se,sw,se,swn,sn,s,sn,sn,se,swe,sw,se
